# Generated by Django 3.2.6 on 2021-08-31 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha De Nacimiento')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('gender', models.CharField(default='male', max_length=50, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Celular')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['names'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sale', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha De Venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.client')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Producto')),
                ('mark', models.CharField(default='', max_length=50, unique=True, verbose_name='Marca del Producto')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='detSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.sales')),
            ],
            options={
                'verbose_name': 'detVenta',
                'verbose_name_plural': 'detVentas',
                'ordering': ['id'],
            },
        ),
    ]
