# Generated by Django 3.2.7 on 2021-10-10 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(max_length=250, verbose_name='Tipo de pago')),
                ('taxPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Order received', 'Orden recibida'), ('Order In Process', 'Orden En Proceso'), ('Order On The Way', 'Orden En Camino'), ('Order Completed', 'Orden Completada'), ('Order canceled', 'Orden Cancelada')], max_length=100)),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(default='', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('brand', models.CharField(default='', max_length=50, verbose_name='Marca del Producto')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('numReviews', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Visitas')),
                ('salePrice', models.PositiveIntegerField(default=0, verbose_name='Precio')),
                ('offerPrice', models.PositiveIntegerField(default=0, verbose_name='Oferta')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('warranty', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Garantia')),
                ('dispachTime', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Tiempo de envio')),
                ('statusProduct', models.BooleanField(blank=True, default='', null=True, verbose_name='Estado')),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='Rut')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('phone', models.CharField(default='', max_length=12, unique=True, verbose_name='Celular')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Dirección')),
                ('email', models.EmailField(default='', max_length=100, unique=True, verbose_name='Email')),
                ('detailProduct', models.TextField(default='', verbose_name='Detalle de los productos')),
                ('timeDelivery', models.DateField(verbose_name='Fecha de Entrega(dd/mm/yyyy)')),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ciudad')),
                ('postalCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ciudad')),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.orders')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDetail', models.IntegerField(blank=True, default=0, null=True)),
                ('paymentMethod', models.CharField(max_length=250, verbose_name='Tipo de pago')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.orders')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('comments', models.TextField(default='', verbose_name='Descripción')),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.supplier'),
        ),
        migrations.CreateModel(
            name='OderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('Orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.orders')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.product')),
            ],
            options={
                'verbose_name': 'Orden de articulo',
                'verbose_name_plural': 'Ordenes de articulos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatchNum', models.IntegerField(blank=True, default=0, null=True)),
                ('dispatchDate', models.DateField(auto_now=True)),
                ('destinationCity', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ciudad de destino')),
                ('destinationAddress', models.CharField(blank=True, max_length=400, null=True, verbose_name='Dirección de destino')),
                ('dispatched_By', models.CharField(blank=True, max_length=400, null=True, verbose_name='Despachado por:')),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('shippingadress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.shippingaddress')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cliente')),
                ('phone', models.CharField(default='', max_length=12, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo')),
                ('typeClaim', models.CharField(choices=[('Consulta', 'Consulta'), ('Reclamo', 'Reclamo'), ('Sugerencía', 'Sugerencía'), ('Felicitaciones', 'Felicitaciones')], default='', max_length=100)),
                ('claim', models.CharField(max_length=500, verbose_name='Reclamo')),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('Password', models.CharField(default='', max_length=200, verbose_name='Contraseña')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
