# Generated by Django 3.2.7 on 2021-11-21 00:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio')),
                ('qty', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('subtotal', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SubTotal')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, null=True, unique=True, verbose_name='Rut')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Nombre del Cliente')),
                ('second_name', models.CharField(max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('pather_last_name', models.CharField(default='', max_length=100, null=True, verbose_name='Apellido Paterno')),
                ('mother_last_name', models.CharField(default='', max_length=100, null=True, verbose_name='Apellido Materno')),
                ('phone', models.CharField(default='', max_length=9, null=True, unique=True, verbose_name='Celular')),
                ('email', models.EmailField(default='', max_length=50, null=True, unique=True, verbose_name='Correo Electronico')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dispatcher')),
                ('createdAt', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Despachador',
                'verbose_name_plural': 'Despachadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio De Envio')),
                ('subtotal', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SubTotal')),
                ('total', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('createdAt', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='client',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='report',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='client',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.RemoveField(
            model_name='oderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='taxPrice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Prefiero No Decir', 'Prefiero No Decir')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='mother_last_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='client',
            name='pather_last_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=9, null=True, unique=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='client',
            name='rut',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='Rut'),
        ),
        migrations.AddField(
            model_name='client',
            name='second_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AddField(
            model_name='orders',
            name='arrivalDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Llegada de los Productos'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shippingValue',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio De Envio'),
        ),
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Producto En Oferta'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='mother_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pather_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='second_name',
            field=models.CharField(default='', max_length=50, verbose_name='Segundo Nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='createdAt',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=50, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='isDelivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='isPaid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shippingPrice',
            field=models.PositiveIntegerField(default=0, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Orden A Despacho', 'Orden A Despacho'), ('Orden En Proceso', 'Orden En Proceso'), ('Orden En Camino', 'Orden En Camino'), ('Orden Completada', 'Orden Completada'), ('Orden Cancelada', 'Orden Cancelada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='totalPrice',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='statusProduct',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='detailProduct',
            field=models.TextField(default='Nombre del Producto: \n1)\n2)\n3) \n Cantidad de dichos productos: \n1)\n2)\n3) ', verbose_name='Detalle de los productos'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='', max_length=9, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='timeDelivery',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Entrega de los Productos'),
        ),
        migrations.DeleteModel(
            name='Dispatch',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='SalesDetail',
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.client'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.product'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.sale'),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.dispatcher'),
        ),
    ]
