# Generated by Django 3.2.7 on 2021-11-06 03:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='client',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='oderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='client',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(default='', max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='isDelivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='isPaid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Orden recibida', 'Orden recibida'), ('Orden En Proceso', 'Orden En Proceso'), ('Orden En Camino', 'Orden En Camino'), ('Orden Completada', 'Orden Completada'), ('Orden Cancelada', 'Orden Cancelada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='statusProduct',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='timeDelivery',
            field=models.DateField(verbose_name='Fecha de Entrega'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
