# Generated by Django 3.2.7 on 2021-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='Rut')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('phone', models.CharField(default='', max_length=12, unique=True, verbose_name='Celular')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Dirección')),
                ('email', models.EmailField(default='', max_length=100, unique=True, verbose_name='Email')),
                ('detailProduct', models.TextField(default='', verbose_name='Descripción')),
                ('timeDelivery', models.CharField(default='', max_length=250, verbose_name='Tiempo de Entrega')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
    ]
