# Generated by Django 3.2.6 on 2021-09-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.CharField(default='', max_length=50, verbose_name='Marca del Producto'),
        ),
    ]
