# Generated by Django 3.2.7 on 2021-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0002_auto_20211120_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ciudad'),
        ),
    ]
