# Generated by Django 3.2.6 on 2021-09-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PuntoVentas', '0002_alter_product_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.CharField(max_length=200)),
                ('shipping_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electronico')),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('order_status', models.CharField(choices=[('Orden recivida', 'Orden recivida'), ('Orden En Proceso', 'Orden En Proceso'), ('Orden En Camino', 'Orden En Camino'), ('Orden Completada', 'Orden Completada'), ('Orden Cancelada', 'Orden Cancelada')], max_length=50)),
                ('date_create', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.cart')),
            ],
        ),
        migrations.RemoveField(
            model_name='detsales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='detsales',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='client',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='marked_price',
            field=models.PositiveIntegerField(default=0, max_length=20, verbose_name='Precio De Mercado'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.PositiveIntegerField(default=0, max_length=20, verbose_name='Precio de Venta'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='detSales',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PuntoVentas.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.customer'),
        ),
    ]
