# Generated by Django 3.2.7 on 2021-11-08 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0002_auto_20211106_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shippingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='detailProduct',
            field=models.TextField(default='Nombre del Producto: \n1)\n2)\n3) \n Cantidad de dichos productos: \n1)\n2)\n3) ', verbose_name='Detalle de los productos'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='timeDelivery',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Entrega de los Productos'),
        ),
    ]
