# Generated by Django 3.2.7 on 2021-11-23 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0003_auto_20211121_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro'),
        ),
    ]
