# Generated by Django 3.2.7 on 2021-10-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0003_auto_20211018_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
