# Generated by Django 3.2.7 on 2021-10-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0003_auto_20211010_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderitem',
            name='name',
        ),
    ]
