# Generated by Django 3.2.6 on 2021-09-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0003_auto_20210903_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Visitas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Garantia'),
        ),
    ]
