# Generated by Django 3.2.7 on 2021-10-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0003_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='date_create',
            new_name='createdAt',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(default='', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('brand', models.CharField(default='', max_length=50, verbose_name='Marca del Producto')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('numReviews', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Visitas')),
                ('salePrice', models.PositiveIntegerField(default=0, verbose_name='Precio')),
                ('offerPrice', models.PositiveIntegerField(default=0, verbose_name='Oferta')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('warranty', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Garantia')),
                ('dispachTime', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Tiempo de envio')),
                ('statusProduct', models.BooleanField(blank=True, default='', null=True, verbose_name='Estado')),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.category')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.supplier')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
