# Generated by Django 3.2.7 on 2021-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0004_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderitem',
            name='image',
        ),
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
