# Generated by Django 3.2.7 on 2021-12-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0004_auto_20211122_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='file', verbose_name='Subir Archivo')),
                ('createdAt', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Archivo Plano',
                'verbose_name_plural': 'Archivos Planos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='claim',
            field=models.CharField(max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=9, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='typeClaim',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Reclamo', 'Reclamo'), ('Sugerencía', 'Sugerencía'), ('Felicitaciones', 'Felicitaciones')], default='', max_length=100, verbose_name='Tipo de Solicitud'),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dispatcher', verbose_name='imagen'),
        ),
    ]
