# Generated by Django 3.2.7 on 2021-10-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0004_remove_oderitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.client'),
        ),
    ]
