# Generated by Django 3.2.7 on 2021-12-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0005_auto_20211206_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatfile',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='flatfile',
            name='file',
            field=models.FileField(upload_to='file', verbose_name='Subir Archivo'),
        ),
        migrations.AlterField(
            model_name='flatfile',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Titulo'),
        ),
    ]
