# Generated by Django 3.2.7 on 2021-11-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0005_auto_20211108_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='taxPrice',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='totalPrice',
        ),
    ]
