# Generated by Django 3.2.7 on 2021-10-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0005_auto_20211010_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oderitem',
            old_name='Orders',
            new_name='order',
        ),
    ]
