# Generated by Django 3.2.7 on 2021-10-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0005_auto_20211029_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='statusProduct',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Estado'),
        ),
    ]
