# Generated by Django 3.2.7 on 2021-10-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0006_alter_product_statusproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='isDelivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='isPaid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
