# Generated by Django 3.2.7 on 2021-12-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0007_flatfile_typefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
