# Generated by Django 3.2.7 on 2021-12-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0008_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.CharField(max_length=200, unique=True, verbose_name='Empresa'),
        ),
    ]
