# Generated by Django 3.2.7 on 2021-10-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0008_auto_20211003_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cliente')),
                ('claim', models.CharField(max_length=500, verbose_name='Reclamo')),
                ('createdAt', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PuntoVentas.users')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['name'],
            },
        ),
    ]
