# Generated by Django 3.2.7 on 2021-10-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0009_auto_20211029_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Orden recibida', 'Orden recibida'), ('Orden En Proceso', 'Orden En Proceso'), ('Orden En Camino', 'Orden En Camino'), ('Orden Completada', 'Orden Completada'), ('Orden Cancelada', 'Orden Cancelada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Postal'),
        ),
    ]
