# Generated by Django 3.2.7 on 2021-12-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PuntoVentas', '0010_orders_dispatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dispatch',
        ),
    ]
